# Generated by Django 4.1.2 on 2024-07-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuestilo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
